### ISSUE TITLE
Support for netty 4.1x

### ISSUE THREAD

**Issue by darkwitch** [Shevchik/UdpServerSocketChannel#2]
Support for 4.1 would be really helpfull - I ported it myself, but after changes from https://github.com/Shevchik/UdpServerSocketChannel/issues/1 I'd better stick with 4.0 for now.

**Comment by Shevchik** [comment]
I guess i should move current 4.0 to a separate branch first, and then update man to 4.1

**Comment by Shevchik** [comment]
Updated.
