### ISSUE TITLE
Incorrect data received after few frames passed

### ISSUE THREAD

**Issue by darkwitch** [Shevchik/UdpServerSocketChannel#4]
Hi,

I've just detected a nasty bug, when every once in a while we get a partial data in channelRead0. 

I've forked your project and created a failing JUnit test for that here https://github.com/darkwitch/UdpServerSocketChannel/commit/fde64fb962da69ada872e34c0c5c9dc55aef21eb. 

Attached is a modified version of the test that will run out of the box, so that you do not have to change your project. It requires java8 however.

[IncorrectFrameReceivedTest.java.txt](https://github.com/Shevchik/UdpServerSocketChannel/files/858038/IncorrectFrameReceivedTest.java.txt)

**Comment by Shevchik** [comment]
Netty has a thing called a receive byte buf allocator. It tries to predict inbound buffer size, and sometimes that may be not enough for a full message. Set a FixedByteBufAllocator with size of 1500 (max possible mtu under normal conditions) on server create to avoid this.

**Comment by Shevchik** [comment]
Should be now fixed on both branches (will have to add a separate jenkins project for 4.0 branch)
